---
- name: Install epel on all hosts
  hosts: wordpress
  tasks: 
    - yum:
        name: epel-release
        state: latest
      become: yes

- name: install mariadb
  hosts: db
  become: yes

  vars_files:
    - ../vars/wordpress.yaml

  tasks:
    - yum:
        name: mariadb-server
        state: latest

    - systemd:
        name: mariadb
        enabled: yes
        state: started

    - mysql_user:
        name: '{{ mariadb_wordpress_user }}'
        password: '{{ mariadb_wordpress_pass }}'
        priv: '*.*:ALL'
        state: present

    - name: create the wordpress database
      mysql_db:
        name: '{{ mariadb_wordpress_dbname }}'
        state: present

- name: install php-fpm
  hosts: php-fpm
  become: yes
  tasks:
    - yum:
        name: php-fpm
        state: latest
    - lineinfile:
        path: /etc/php-fpm.d/www.conf
        regexp: '^listen ='
        line: "listen = {{ hostvars[groups['php-fpm'][0]]['ansible_enp0s8']['ipv4']['address'] }}:9000"
      notify: restart php-fpm
    - lineinfile:
        path: /etc/php-fpm.d/www.conf
        regexp: '^listen.allowed_clients ='
        line: "listen.allowed_clients = {{ hostvars[groups['web'][0]]['ansible_enp0s8']['ipv4']['address'] }}"
      notify: restart php-fpm
    - systemd:
        name: php-fpm
        enabled: yes
  handlers:
    - name: restart php-fpm
      service:
        name: php-fpm
        enabled: yes
        state: restarted

- name: Install/Configure nginx
  become: yes
  hosts: web

  vars_files:
    - ../vars/wordpress.yaml

  tasks: 
    - name: Install nginx
      yum:
        name: nginx
        state: latest
    - name: Start nginx service via systemd and ensure its started during boot
      systemd:
        name: nginx
        enabled: yes
        state: started
    - name: Add sites-enabled support to nginx
      file:
        path: /etc/nginx/sites-enabled
        state: directory
    - name: Add this to nginx conf file
      lineinfile:
        path: /etc/nginx/nginx.conf
        insertbefore: "^\\s*server {"
        line: 'include /etc/nginx/sites-enabled/*;'
      notify: reload nginx
    - name: create wordpress site
      template:
        src: ../templates/wordpress.nginx.j2
        dest: /etc/nginx/sites-enabled/wordpress
        # dest: /tmp/wordpress
      vars:
        upstream_addr: "{{ hostvars[groups['php-fpm'][0]]['ansible_enp0s8']['ipv4']['address'] }}"
      notify: reload nginx

    - name: create www dir
      file:
        path: /var/www/
        state: directory

    - name: download/unarchive wp
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /var/www
        remote_src: true
        validate_certs: no

    - name: create wordpress config file
      template:
        src: ../templates/wp-config-sample.php.j2
        dest: /var/www/wordpress/wp-config.php
      vars:
        mariadb_wordpress_dbhost: "{{ hostvars[groups['db'][0]]['ansible_enp0s8']['ipv4']['address'] }}"

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded

