---
- name: Install epel on all hosts
  hosts: wordpress
  tasks: 
    - yum:
        name: epel-release
        state: latest
      become: yes

- name: install mariadb
  hosts: db
  become: yes

  vars_files:
    - ../vars/wordpress.yaml

  tasks:
    - yum:
        name: mariadb-server
        state: latest

    - systemd:
        name: mariadb
        enabled: yes
        state: started

    - mysql_user:
        name: '{{ mariadb_wordpress_user }}'
        password: '{{ mariadb_wordpress_pass }}'
        priv: '*.*:ALL'
        state: present

- name: install php-fpm
  hosts: php-fpm
  become: yes
  tasks:
    - yum:
        name: php-fpm
        state: latest
    - lineinfile:
        path: /etc/php-fpm.d/www.conf
        regexp: '^listen ='
        line: "listen = '{{ hostvars[groups['php-fpm'][0]]['ansible_enp0s8']['ipv4']['address'] }}'"
    - lineinfile:
        path: /etc/php-fpm.d/www.conf
        regexp: '^listen.allowed_clients ='
        line: "listen.allowed_clients = '{{ hostvars[groups['web'][0]]['ansible_enp0s8']['ipv4']['address'] }}'"
    - systemd:
        name: php-fpm
        enabled: yes
        state: started

